### ISSUE TITLE
/vp1p1/caliperEntityLtiSession.json @context value should point to the v1p1 context not v1p1/ToolLaunchProfile-extension context

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-common-fixtures#201]
Although the fixture's  `LtiSession.messageParameters` values have been modified to reflect LTI 1.3 key/value pairs both the  `LtiSession` term  and the `messageParameters` values remain v1p1 terms.  

Moreover, while the ToolLaunch Profile references LTI 1.3 it does not require that `LtiSession.messageParameters` object values conform to the LTI 1.3 spec.

Given the above, the `@context` value, in my opinion, should remain

"http://purl.imsglobal.org/ctx/caliper/v1p1"

rather than 

"http://purl.imsglobal.org/ctx/caliper/v1p1/ToolLaunchProfile-extension"

**Comment by ViktorHaag** [comment]
As long as this doesn't cause problems with mixing context values within Event objects, that's fine with me.

**Comment by arwhyte** [comment]
Resolved by #202
