### ISSUE TITLE
SearchResponse and Query entities have the same id

### ISSUE THREAD

**Issue by andrew-gardener** [IMSGlobal/caliper-common-fixtures#205]
`caliperEntitySearchResponse.json`

https://github.com/IMSGlobal/caliper-common-fixtures/blob/develop/v1p1/caliperEntitySearchResponse.json#L3 - https://github.com/IMSGlobal/caliper-common-fixtures/blob/develop/v1p1/caliperEntitySearchResponse.json#L14

`caliperEventSearchSearched.json`

https://github.com/IMSGlobal/caliper-common-fixtures/blob/develop/v1p1/caliperEventSearchSearched.json#L16 - https://github.com/IMSGlobal/caliper-common-fixtures/blob/develop/v1p1/caliperEventSearchSearched.json#L21

Is this intentional?

**Comment by arwhyte** [comment]
When I visit the develop branch `/v1/p1` directory, I see only

https://github.com/IMSGlobal/caliper-common-fixtures/blob/develop/v1p1/caliperEntitySearchResponse.json

https://github.com/IMSGlobal/caliper-common-fixtures/blob/develop/v1p1/caliperEventSearchSearched.json

**Comment by andrew-gardener** [comment]
Yes, in both those files the id for the SearchResponse is the same as the id for the Query entity (I just linked directly to the lines with the ids in both files)

**Comment by arwhyte** [comment]
Ah.  That is intentional (at least for the moment).  I can adjust the `SearchResponse` identifier, perhaps to:

"https://example.edu/users/554433/response?query=IMS%20AND%20%28Caliper%20OR%20Analytics%29",

What say you?

**Comment by andrew-gardener** [comment]
That change sounds good to me.

On the intentional side of things, it makes more sense to me to not reuse IRI between entities since the IRI is supposed to represent a particular thing and in this case it could represent two different things. 

Anyways, I actually caught this when working on the caliper-ruby implementation since it has a lot of optimizations in serializing and deserializing that assumes ids are unique and belong to the same entity.

**Comment by ViktorHaag** [comment]
This issue has been merged, and we should close it.
