### ISSUE TITLE
ResourceManagementEvent fixtures contain inconsistent IRIs

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-common-fixtures#207]
The ResourceManagementEvent fixtures contain inconsistent IRIs.  The term should be assumed to be 2018 (given other IRIs) and dates not 2016:

```
"group": {
    "id": "https://example.edu/terms/201601/courses/7/sections/1",
    "type": "CourseSection",
    "courseNumber": "CPS 435-01",
    "academicSession": "Fall 2018"
  },
  "membership": {
    "id": "https://example.edu/terms/201601/courses/7/sections/1/rosters/1",
    "type": "Membership",
    "member": "https://example.edu/users/554433",
    "organization": "https://example.edu/terms/201601/courses/7/sections/1",
    "roles": [ "Instructor" ],
    "status": "Active",
    "dateCreated": "2018-08-01T06:00:00.000Z"
  }
```

Change to

```
"group": {
    "id": "https://example.edu/terms/201801/courses/7/sections/1",
    "type": "CourseSection",
    "courseNumber": "CPS 435-01",
    "academicSession": "Fall 2018"
  },
  "membership": {
    "id": "https://example.edu/terms/201801/courses/7/sections/1/rosters/1",
    "type": "Membership",
    "member": "https://example.edu/users/554433",
    "organization": "https://example.edu/terms/201801/courses/7/sections/1",
    "roles": [ "Instructor" ],
    "status": "Active",
    "dateCreated": "2018-08-01T06:00:00.000Z"
  },
```
PR on the way.

**Comment by ViktorHaag** [comment]
That sounds good. I think I just grabbed these out of the examples in the spec; we should that the spec examples match the fixtures, @arwhyte ?

**Comment by arwhyte** [comment]
@ViktorHaag -- yes any changes we make to the fixtures should be reflected in the docs if they are used as examples.

**Comment by ViktorHaag** [comment]
@arwhyte closing as merged.

**Comment by ViktorHaag** [comment]
Hrm -- re-opening. It looks to me like the merged PR linked to here may not have done an entire sweep on the fixtures in v1p1, so let's leave this open until we've had a chance to discuss what we'd like to do with date maintenance in fixtures, in general (see discussion in pr #209)

**Comment by ViktorHaag** [comment]
Closing because this should get swept up in dealing with #246 and the effort to make the v1p2 fixtures release-ready for Caliper 1.2.
