### ISSUE TITLE
Add a universal identifier field to communicate multiple object sourcedId(s) to downstream systems

### ISSUE THREAD

**Issue by ojurosevic** [IMSGlobal/caliper-common-fixtures#219]
We need to figure out a flexible enough way to communicate multiple object IDs in Caliper messages. 

This is Canvas specific use case I'm looking to solve : 

We need an ability to communicate sis sourcedId for user, courseOffering and courseSection . There are multiple ways of populating sis sourcedId in Canvas, those are : 

1. end user manually creates an object and assigns an arbitrary sis sourcedId
2. automated  SIS Data Import creates objects in bulk with sis sourced Id as a foreign key 
3. object is created when LTI is launched where LTI is primary source of sis sourced id 

There are multiple local Id's in Canvas and I'm sure at some point our end users would like to have an opportunity to receive them in Caliper messages, here is the list of Ids our consumers might be after:

LMS uuid
LTI context Id
SIS sourced Id
Integration Id

**Comment by ViktorHaag** [comment]
I suspect we should merge this with #204 ...

**Comment by arwhyte** [comment]
@ojurosevic issue description moved to https://github.com/IMSGlobal/caliper-central/issues/204 as a comment.  Closing this issue.
